general.import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
#normal.family = "MesloLGS Nerd Font"
size = 16

[env]
TERM = "xterm-256color"
TMUX_CONF = "~/.config/tmux/tmux.conf"

[[keyboard.bindings]]
action = "Paste"
key = "V" 
mods = "Control" 

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "R"
mods = "Control|Shift"




